Misfist/bugfix wp_localize_script
chatwoot/wp-plugin pull request #3
Opened 2023-01-26 03:20 UTC by misfist

Update `wp_localize_script` usage to fix WordPress error:

```
Notice: Function WP_Scripts::localize was called incorrectly. The $l10n parameter must be an array. To pass arbitrary data to scripts, use the wp_add_inline_script() function instead. Please see Debugging in WordPress for more information. (This message was added in version 5.7.0.) in /var/www/html/wp-includes/functions.php on line 5835
```

- [Add link to WordPress function](https://github.com/misfist/wp-chatwoot/commit/bfac481cd02bd770a6d7f1ac073c70a4a1403e78)
   - See https://developer.wordpress.org/reference/functions/wp_localize_script/
- [Change 3rd param to array](https://github.com/misfist/wp-chatwoot/commit/48cd4b18cc54322ccb7b0161ef093603166199ea)
- [Add comment about change](https://github.com/misfist/wp-chatwoot/commit/083f01fee6b670f2278efe0d8e824b6eb771a4bb)
- [WordPress coding standards formatting](https://github.com/misfist/wp-chatwoot/commit/b744e0749b0f552f26f9b8724bc5abd36009aee7)
   - See https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#space-usage

2023-02-22 19:58 UTC, pranavrajs commented
@scmmishra Would you be able to test this change and get it approved?

2023-03-02 14:18 UTC, scmmishra requested changes
The changes look good to go, except for the one typo.

2023-03-02 14:18 UTC, scmmishra commented on chatwoot-plugin.php
> +	$chatwoot_widget_locale   = get_option( 'chatwootWidge tLocale' );
Seems like a typo here

```suggestion
	$chatwoot_widget_locale   = get_option( 'chatwootWidgetLocale' );
```

2023-03-06 07:29 UTC, scmmishra approved these changes

2023-03-06 07:29 UTC, merged

2023-03-06 07:52 UTC, scmmishra commented
Hey @misfist I had to revert the PR, seems like multiple options from the config are not respected. While the `wp_localize_script` requires encapuslation in an array. The injected values are not restructured. See screenshot below, 

<img width="660" alt="image" src="https://user-images.githubusercontent.com/18097732/223049765-45d1d2ea-e130-4c31-afb6-4af7c23747ba.png">

Perhaps a better alternative would be to use `wp_add_inline_script`.